### ISSUE TITLE
Todo: add all current containers to the default ini

### ISSUE THREAD

**Issue by TeoTwawki** [TeoTwawki/LootBox#6]
FFXI has undergone some changes in storage since this was last updated, once bugs with current FFXI client are resolved it'll be time to add those default tabs.

**Comment by TeoTwawki** [comment]
fab53c0f5ba85c556b67a345c1e5bfd090fcd248

Now I need somebody who has actually unlocked their 2nd mog safe and put items in it to verify, and we can call this done.

**Comment by onetimeffxi** [comment]
I am not sure which dat file corresponds to Mog Safe 2 (I assumed is_2.dat). wr.dat is the Mog Wardrobe and does load correctly when added to ini file.

**Comment by TeoTwawki** [comment]
wr.dat is the wardrobe. `is_2.dat` isn't the correct size for a container (valid one will always be 5kb) so  I was presuming `b2.dat` was the 2nd safe, seeing as `bs.dat` was the original safe. Sounds like I got it wrong though.

**Comment by TeoTwawki** [comment]
Here is what we have so far:
```
INVENTORY        is.dat
MOG_SAFE         bs.dat
MOG_SAFE_2       missing
STORAGE          cl.dat
MOG_LOCKER       mb.dat
MOG_SATCHEL      sb.dat
MOG_SACK         sk.dat
MOG_CASE         ca.dat
MOG_WARDROBE     wr.dat
```

**Comment by TeoTwawki** [comment]
@onetimeffxi b2.dat showed nothing for you when you definitely had items in your second mog safe..Is it possible your client hadn't saved to the file cache yet? 
(logging out the character should do the trick)
I ask because I have it showing wind crystals in tests in that file so b2.dat looks like the correct file afterall.

**Comment by TeoTwawki** [comment]
See  #7
